import { CirclePlus } from "lucide-react";

export const ItemModalFormConfig = {
    moduleTitle: 'Manage Item',
    title: 'Create Item',
    description: 'Fill in details below to create a new items.',
    addButton: {
        id: 'add-items',
        label: 'Add',
        className: 'bg-indigo-700 text-white rounded-lg px-4 py-2 hover:bg-indigo-800 cursor-pointer',
        icon: CirclePlus,
        type: 'button',
        variant: 'default',
        permission: 'create-item',
    },
    fields: [
        {
            id: 'outlet_id',
            key: 'outlets',
            name: 'outlet_name',
            label: 'Outlet Name',
            type: 'single-select2',
            placeholder: 'Select Outlet Name',
            autocomplete: 'outlet_id',
            tabIndex: 1,
            autoFocus: true,
            options: []
        },
        {
            id: 'group_id',
            key: 'groups',
            name: 'group_name',
            label: 'Filter by Group',
            type: 'radio',
            placeholder: 'Select Sub Group Name',
            autocomplete: 'group_id',
            tabIndex: 3,
            autoFocus: true,
            options: []
        },
        {
            id: 'subgroup_id',
            key: 'subgroups',
            name: 'subgroup_name',
            label: 'Sub Group',
            type: 'single-select2',
            placeholder: 'Select Sub Group Name',
            autocomplete: 'subgroup_id',
            tabIndex: 3,
            autoFocus: true,
            options: []
        },
        {
            id: 'portion_id',
            key: 'portions',
            name: 'portion_name',
            label: 'Portion Name',
            type: 'single-select2',
            placeholder: 'Select Portion Name',
            autocomplete: 'portion_id',
            tabIndex: 4,
            autoFocus: true,
            options: []
        },
        {
            id: 'item-name',
            key: 'name',
            name: 'name',
            label: 'Item Name',
            type: 'text',
            className: 'border rounded-md px-2',
            placeholder: 'Enter Item Name',
            autocomplete: 'name',
            tabIndex: 5,
            autoFocus: true,
        },
        {
            id: 'description',
            key: 'description',
            name: 'description',
            label: 'Description Name',
            type: 'textarea',
            className: 'border rounded-md px-2',
            placeholder: 'Enter Description',
            autocomplete: 'description',
            tabIndex: 6,
            rows: 2,
            autoFocus: true,
        },
        {
            id: 'currency_id',
            key: 'currencies',
            name: 'currency_name',
            label: 'Currency Name',
            type: 'single-select2',
            placeholder: 'Select Currency',
            autocomplete: 'currency',
            tabIndex: 7,
            autoFocus: true,
            options: []
        },
        {
            id: 'price_id',
            key: 'price',
            name: 'price',
            label: 'Price',
            type: 'number',
            placeholder: 'Enter outlet price',
            autocomplete: 'price',
            tabIndex: 8,
            autoFocus: true,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'happy_hour_price_id',
            key: 'happy_hour_price',
            name: 'happy_hour_price',
            label: 'Happy Hour Price',
            type: 'number',
            placeholder: 'Enter Happy Hour Price',
            autocomplete: 'happy_hour_price',
            tabIndex: 8,
            autoFocus: true,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'cost_percentage_id',
            key: 'cost_percentage',
            name: 'cost_percentage',
            label: 'Cost Percentage',
            type: 'text',
            placeholder: 'Cost Percentage',
            autocomplete: 'cost_percentage',
            tabIndex: 8,
            autoFocus: true,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'recipe_code_id',
            key: 'recipe_code',
            name: 'recipe_code',
            label: 'Recipe Code',
            type: 'number',
            placeholder: 'Recipe Code',
            autocomplete: 'recipe_code',
            tabIndex: 8,
            autoFocus: true,
            className: 'rounded border p-2 w-full',
        },
        {
            id: 'image_path_id',
            key: 'image_path',
            name: 'image_path',
            label: 'Image Path',
            type: 'file',
            placeholder: 'Enter Image Path',
            autocomplete: 'Image Path',
            tabIndex: 8,
            autoFocus: true,
            className: 'rounded border p-2 w-full',
        },
    ],
    buttons: [
        {
            key: 'cancel',
            type: 'button',
            label: 'Cancel',
            variant: 'ghost',
            className: 'bg-gray-300 text-gray-700 rounded-lg px-4 py-2 hover:bg-gray-400 cursor-pointer',
        },
        {
            key: 'submit',
            type: 'submit',
            label: 'Save',
            variant: 'default',
            className: 'cursor-pointer',
        },
    ],
}